/**
 * Lightweight CUID-like ID generator.
 * Produces a collision-resistant, URL-safe, roughly time-sortable identifier.
 * Compatible with the IDs previously generated by Prisma's @default(cuid()).
 */

import crypto from "node:crypto";

const BASE36 = "0123456789abcdefghijklmnopqrstuvwxyz";

let counter = 0;

function pad(num: number, size: number): string {
  const s = num.toString(36);
  return s.length >= size ? s : "0".repeat(size - s.length) + s;
}

function fingerprint(): string {
  const pid = typeof process !== "undefined" ? process.pid : 0;
  const hostname =
    typeof process !== "undefined" && process.env["HOSTNAME"]
      ? process.env["HOSTNAME"]
      : "localhost";
  const hostId = hostname.split("").reduce((acc, ch) => acc + ch.charCodeAt(0), hostname.length);
  return pad(pid, 2) + pad(hostId, 2);
}

function randomBlock(): string {
  const bytes = crypto.randomBytes(4);
  let result = "";
  for (const b of bytes) {
    result += BASE36[b % 36];
  }
  return result;
}

/**
 * Returns a function that generates a unique CUID string each time it is called.
 * Suitable for use as a Drizzle `$defaultFn`.
 */
export function createId(): string {
  const timestamp = pad(Date.now(), 8);
  const count = pad(counter++, 4);
  const fp = fingerprint();
  const random = randomBlock() + randomBlock();
  return "c" + timestamp + count + fp + random;
}
